development:
    clickatell_api_id: YOUR_ID_HERE
    clickatell_username: YOUR_USERNAME_HERE
    clickatell_password: YOUR_PASSWORD_HERE

test:
    clickatell_api_id: YOUR_ID_HERE
    clickatell_username: YOUR_USERNAME_HERE
    clickatell_password: YOUR_PASSWORD_HERE
        
production:
    clickatell_api_id: YOUR_ID_HERE
    clickatell_username: YOUR_USERNAME_HERE
    clickatell_password: YOUR_PASSWORD_HERE